In [ ]:
import pandas as pd
from futu import *
import numpy as np

# 获取历史数据
def fetch_data(ticker, start, end):
    quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111) 
    ret, df, page_req_key = quote_ctx.request_history_kline('HK.0'+ticker, 
                                                            start=str(start), 
                                                            end= str(end), 
                                                            max_count= None, 
                                                            fields=[KL_FIELD.DATE_TIME,
                                                                    KL_FIELD.OPEN,
                                                                    KL_FIELD.HIGH,
                                                                    KL_FIELD.LOW,
                                                                    KL_FIELD.CLOSE,
                                                                    KL_FIELD.TRADE_VOL])
    if ret !=RET_OK:
        print('error: ', df)
    else:
        df = df.rename(columns={"time_key":"date"})
        df["date"] = pd.to_datetime(df["date"]).dt.date
    return df

# 计算移动平均线
def calculate_moving_averages(data, short_window=5, medium_window=10, long_window=20):
    data['Short_MA'] = data['close'].rolling(window=short_window).mean()
    data['Medium_MA'] = data['close'].rolling(window=medium_window).mean()
    data['Long_MA'] = data['close'].rolling(window=long_window).mean()
    return data

# 检测刚刚呈现多头排列
def check_recent_bullish_alignment(data):
    data['Bullish'] = (data['Short_MA'] > data['Medium_MA']) & (data['Medium_MA'] > data['Long_MA'])
    
    # 检测刚刚形成多头排列
    data['Turn_Bullish'] = (data['Bullish']) & ((~data['Bullish']).shift(1))
    sel_data = data[data.Turn_Bullish]['close']
    data['Just_Bullish'] = False
    id = sel_data[sel_data < sel_data.shift(1)].index
    data.loc[id,'Just_Bullish'] = True
    return data

# 主程序
if __name__ == "__main__":
    # 获取数据
    symbol = '0981'
    start_date = '2021-01-01'
    end_date = '2022-01-01'
    data = fetch_data(symbol, start_date, end_date)

    # 计算移动平均线
    data = calculate_moving_averages(data)

    # 检测刚刚呈现多头排列
    data = check_recent_bullish_alignment(data)

    # 输出结果
    recent_bullish_days = data[data['Just_Bullish']]
    print("刚刚呈现多头排列的日期：")
    print(recent_bullish_days.index)

    import matplotlib.pyplot as plt
    plt.plot(data.date, data.close)
    plt.plot(data.date, data.Short_MA, color='orange')
    plt.plot(data.date, data.Medium_MA, color='green')
    plt.plot(data.date, data.Long_MA, color='red')
    plt.scatter(data.date[recent_bullish_days.index], data.close[recent_bullish_days.index], color='r')

In [39]:
## ***************** Web srape stocks in each sector of US market from yahoo finance ******************
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://finance.yahoo.com/research-hub/screener/sec-ind_sec-largest-equities_utilities"
# Add a user-agent to your request to be polite and identify your scraper
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36'}

# Fetch the HTML content
response = requests.get(url, headers=headers)
html_content = response.text

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')

# The website uses JavaScript to load some content, so the initial request might not capture all data.
# For dynamic websites, you might need Selenium.
# However, you can try to find the table directly. Inspect the page to find the table's class or id.
# For example, let's assume the table has a class "table-responsive" or similar (you need to inspect the actual page source)
table = soup.find('table') # This class is an example

# If the table is found, you can use pandas to read it easily
if table:
    # Use pandas to read the HTML table directly into a DataFrame
    # Note: pd.read_html often requires the html5lib parser to be installed (pip install html5lib)
    df = pd.read_html(str(table))[0]
    tmp = df[['Symbol','Name','Market Cap','Sector']].rename(columns={'Symbol':'code','Name':'name','Market Cap':'market_cap','Sector':'sector'}).head(25)
    tmp['code']= tmp.code.apply(lambda x: x.split(' ')[-1])
    file_path = './data/code_pool_us.csv'

    # Check if the file already exists
    if not os.path.exists(file_path):
        # If file doesn't exist, write with header (mode='w' is default)
        tmp.to_csv(file_path, mode='w', header=True, index=False)
    else:
        # If file exists, append without writing the header again
        tmp.to_csv(file_path, mode='a', header=False, index=False)
else:
    print("Table not found. The content might be dynamically loaded with JavaScript.")
    print("Consider using Selenium or an API (if available) for dynamic content.")

/var/folders/9x/bx7xlv0n3dng9qnrzlpnm52w0000gn/T/ipykernel_3081/1018733760.py:27: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [ ]:
## ***************** Web srape stocks in each sector of HK market from trading view ******************
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re,os

url = "https://www.tradingview.com/markets/stocks-hong-kong/sectorandindustry-sector/miscellaneous"
# Add a user-agent to your request to be polite and identify your scraper
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36'}

# Fetch the HTML content
response = requests.get(url, headers=headers)
html_content = response.text

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')

# The website uses JavaScript to load some content, so the initial request might not capture all data.
# For dynamic websites, you might need Selenium.
# However, you can try to find the table directly. Inspect the page to find the table's class or id.
# For example, let's assume the table has a class "table-responsive" or similar (you need to inspect the actual page source)
table = soup.find('table') # This class is an example

# If the table is found, you can use pandas to read it easily
if table:
    # Use pandas to read the HTML table directly into a DataFrame
    # Note: pd.read_html often requires the html5lib parser to be installed (pip install html5lib)
    df = pd.read_html(str(table))[0]
    tmp = pd.DataFrame()
    tmp['code'] = df.Symbol.apply(lambda x: re.match(r"(\d+)(.*)", x).groups()[0]).str.zfill(4)
    tmp['name'] = df.Symbol.apply(lambda x: re.match(r"(\d+)(.*)", x).groups()[1])
    tmp['market_cap'] = df['Market cap']
    tmp['sector'] = 'Consumer Defensive'
    tmp = tmp.iloc[:25]

    file_path = './data/code_pool_hk.csv'

    # Check if the file already exists
    if not os.path.exists(file_path):
        # If file doesn't exist, write with header (mode='w' is default)
        tmp.to_csv(file_path, mode='w', header=True, index=False)
    else:
        # If file exists, append without writing the header again
        tmp.to_csv(file_path, mode='a', header=False, index=False)
else:
    print("Table not found. The content might be dynamically loaded with JavaScript.")
    print("Consider using Selenium or an API (if available) for dynamic content.")

/var/folders/9x/bx7xlv0n3dng9qnrzlpnm52w0000gn/T/ipykernel_3081/3983194140.py:27: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [42]:
df = pd.read_csv('./data/code_pool_hk.csv')
df['code'] = df.code.astype(str).str.zfill(4)
df.to_csv('./data/code_pool_hk.csv', index=False)

In [ ]:
from futu import *

with open(f'./data/code_pool_us.txt','r') as fp:
    list = [line.rstrip() for line in fp]
code_list = ['US.'+code for code in list]
# The API limits requests to 400 targets at a time, but get_owner_plate supports the whole list
# if you need to chunk the requests, you could do so here.
# However, the code below processes the entire list.
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)

ret, data = quote_ctx.get_owner_plate(code_list)

if ret != RET_OK:
    print('error:', data)
quote_ctx.close()

sector_mapping = pd.read_csv("./data/sector_mapping.csv")
df = data.set_index('plate_type').loc['INDUSTRY']
print(df.plate_name.unique())
sector_df = df.merge(sector_mapping, on='plate_name', how='inner')
sector_df['code'] = sector_df.code.apply(lambda x: x[4:])
sector_df.to_csv('us_sector_mapping.csv')

In [46]:
df = pd.read_csv("./data/code_pool_hk.csv")
df[df.code.duplicated()]

     code                     name   market_cap      sector
154  2228  XtalPi Holdings Limited  56.05 B HKD  Healthcare

In [14]:
sector_mapping_hk = pd.read_csv("./data/sector_mapping_hk.csv")
sector_mapping_us = pd.read_csv("./data/sector_mapping_us.csv")

sector_mapping = pd.concat([sector_mapping_hk[['plate_name','sector']],sector_mapping_us[['plate_name','sector']]],ignore_index=True)

sector_mapping.drop_duplicates(inplace=True,ignore_index=True)


sector_mapping[['plate_name','sector']].to_csv("./data/sector_mapping.csv")

In [ ]:
from futu import *
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111) 
ret, data = quote_ctx.get_stock_basicinfo(Market.HK, stock_type=SecurityType.ETF, code_list=None)

if ret == RET_OK:
    print(data.columns)
    print(data[['code','name']])
else:
    print(f"Error retrieving data: {data}")

# Close the connection
quote_ctx.close()

2026-01-26 11:59:25,129 | 2557 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=18, host=127.0.0.1, port=11111, user_id=33457180
获取股票所属板块接口不支持ETFs类型
Index(['code', 'name', 'lot_size', 'stock_type', 'stock_child_type',
       'stock_owner', 'option_type', 'strike_time', 'strike_price',
       'suspension', 'listing_date', 'stock_id', 'delisting',
       'index_option_type', 'main_contract', 'last_trade_time',
       'exchange_type'],
      dtype='object')
         code      name
0    HK.00405  越秀房产信托基金
1    HK.00435   阳光房地产基金
2    HK.00778    置富产业信托
3    HK.00808    泓富产业信托
4    HK.00820  汇丰中国翔龙基金
..        ...       ...
395  HK.83460   华夏SOL-R
396  HK.83461  A华夏人币数-R
397  HK.83483  易方达高股息-R
398  HK.83489   易方达AI-R
399  HK.87001    汇贤产业信托

[400 rows x 2 columns]
2026-01-26 11:59:26,066 | 2557 | [open_context_base.py] on_disconnect:383: Disconnected: conn_id=18

In [ ]:
from futu import *
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111) 
code = 'HK.VXHSI'  # Code for Hang Seng Volatility Index
ret, data = quote_ctx.get_market_snapshot([code])

if ret == RET_OK:
    print(f"VXHSI Value: {data['lastPrice'][0]}")
else:
    print(f"Error retrieving data: {data}")

# Close the connection
quote_ctx.close()

In [110]:
## ******* get SPX 500 constituent stocks for US market using futu api *******
from futu import *
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)
index_plate_code = 'US..NDX' # Confirm this is the correct HSI code
ret, data = quote_ctx.get_plate_stock(index_plate_code)
code_list = data.code.to_list()
ret, data = quote_ctx.get_owner_plate(code_list)
tmp = data[data.plate_type=='INDUSTRY'][['code','name','plate_name']]

# # plate_data = []
# # ret, data = quote_ctx.get_owner_plate(code_list[:200])
# # plate_data.append(data[data.plate_type=='INDUSTRY'][['code','name','plate_name']])
# # ret, data = quote_ctx.get_owner_plate(code_list[200:400])
# # plate_data.append(data[data.plate_type=='INDUSTRY'][['code','name','plate_name']])
# # ret, data = quote_ctx.get_owner_plate(code_list[400:600])
# # plate_data.append(data[data.plate_type=='INDUSTRY'][['code','name','plate_name']])

# # tmp = pd.concat(plate_data)
tmp.rename(columns={"plate_name":"plate"},inplace=True)
tmp['code'] = tmp.code.apply(lambda x: x[3:])

us_275 = pd.read_csv('./data/code_pool_us_275.csv') #top 25 highest market cap stocks for each sector. Scraped from yahoo finance
df = us_275.merge(tmp, on="code",how='right')
#df.rename(columns={"name_x":"name","name_y":"name_chinese"},inplace=True)

us_nsdq = pd.read_csv('./data/code_pool_us_nsdq.csv')

miss_df = df[['code']].merge(us_nsdq,on=['code'],how='left')
#print(df[df.sector.isna()])

print(miss_df)
df['sector'].fillna(miss_df['sector'],inplace=True)
df.rename(columns={'name_y':'name'},inplace=True)
df[['code','name','plate','sector','market_cap']].to_csv('./data/code_pool_us_new.csv',index=False)
#
#df.to_csv('./data/code_pool_us_ndaq.csv',index=False)

2026-01-23 10:48:22,045 | 2757 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=97, host=127.0.0.1, port=11111, user_id=33457180
     code     name                  sector
0    AAPL       苹果              Technology
1    ABNB      爱彼迎  Consumer Discretionary
2    ADBE    Adobe              Technology
3     ADI      亚德诺              Technology
4     ADP   自动数据处理              Technology
..    ...      ...                     ...
96   WDAY  Workday              Technology
97    WDC      NaN                     NaN
98    WMT      NaN                     NaN
99    XEL   埃克西尔能源               Utilities
100    ZS  Zscaler              Technology

[101 rows x 3 columns]

In [3]:
import pandas as pd
df = pd.read_csv('./data/code_pool_us.csv')
df.sort_values('sector').to_csv('./data/code_pool_us.csv',index=False)

In [ ]:
from futu import *
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)
code_list = ['US.ADBE'] # Confirm this is the correct HSI code
ret, data = quote_ctx.get_owner_plate(code_list)
sector_data = data[data.plate_type=='INDUSTRY'][['code','name','plate_name']]
print(sector_data)
ret, market_data = quote_ctx.get_market_snapshot(code_list)
sector_data.merge(market_data[['code','total_market_val']], on ='code')

2026-06-03 12:40:29,008 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=6, host=127.0.0.1, port=11111, user_id=33457180
       code   name plate_name
16  US.ADBE  Adobe       应用软件

      code   name plate_name  total_market_val
0  US.ADBE  Adobe       应用软件      1.059449e+11

2026-06-03 18:31:50,185 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=1 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,200 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:31:50,202 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=3 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,202 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:31:50,203 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=2 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,203 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:31:50,204 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=5 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,204 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:31:50,205 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=4 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,206 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:31:50,206 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=6 reason=CloseReason.ReadFail msg=[Errno 54] Connection reset by peer
2026-06-03 18:31:50,207 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:35:57,685 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=7, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:35:57,693 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=11, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:35:57,694 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=8, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:35:57,695 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=12, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:35:57,702 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=10, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:35:57,704 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=9, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 18:51:21,107 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=7 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,108 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:51:21,109 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=10 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,110 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:51:21,111 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=9 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,112 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:51:21,113 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=11 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,113 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:51:21,114 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=8 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,114 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 18:51:21,115 | 15326 | [open_context_base.py] on_disconnect:386: Disconnected: conn_id=12 reason=CloseReason.RemoteClose msg=
2026-06-03 18:51:21,115 | 15326 | [open_context_base.py] _wait_reconnect:482: Wait reconnect in 8 seconds: host=127.0.0.1; port=11111;
2026-06-03 19:07:33,132 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=13, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 19:07:33,136 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=15, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 19:07:33,137 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=16, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 19:07:33,138 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=14, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 19:07:33,138 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=17, host=127.0.0.1, port=11111, user_id=33457180
2026-06-03 19:07:33,139 | 15326 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=18, host=127.0.0.1, port=11111, user_id=33457180

In [1]:
import yfinance as yf, datetime as dt
from data.import_data import Market
codes = Market.US.get_code_pool()["code_list"]

for code in codes:
    ticker = yf.Ticker(code)
    # 获取财报日历
    calendar = ticker.calendar
    try:
        if (calendar['Earnings Date'][0]>dt.date.today()) and (calendar['Earnings Date'][0]<dt.date.today()+dt.timedelta(days=30)):
            print(f"{code} has earnings date within the next 30 days: {calendar['Earnings Date'][0]}")
    except (KeyError, IndexError):
        pass

AVGO has earnings date within the next 30 days: 2026-06-04
CRWD has earnings date within the next 30 days: 2026-06-04
PAYX has earnings date within the next 30 days: 2026-06-25
MU has earnings date within the next 30 days: 2026-06-25
ADBE has earnings date within the next 30 days: 2026-06-12

In [4]:
from portfolio_monitoring import get_capital_flow
get_capital_flow('0883')

2026-02-12 12:08:53,272 | 11639 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=3, host=127.0.0.1, port=11111, user_id=33457180

{'super_big_in_flow': [0.2584, 0.3614, 0.3614, 0.2797, 0.2797],
 'big_in_flow': [0.1323, -0.0274, -0.1217, -0.1091, -0.0623],
 'mid_in_flow': [0.5529, 0.4757, 0.3323, 0.9017, 1.5063],
 'sml_in_flow': [0.4212, 0.3978, 0.3885, 0.4743, 0.5242]}

In [23]:
import serpapi

# Initialize the client with your parameters
client = serpapi.Client(api_key="15e30ce30199c5d1878a249a8011690e212dcfa967ffe08317455a1475d7bada")

# results = client.search({
# "engine":"duckduckgo",
# "q":"current time in Hong Kong",
# "kl":"us-en",
# "search_assist": True
# })
#ai_mode_answer = results.get("search_assist", {}).get("answer", "No answer found")


results = client.search({
    "engine":
"google_ai_mode",
"q":
"weather today in Sha Tin",
"hl":
"en",
"gl":
"us",
"device":
"desktop"
})
# Access structured data generated directly by the search model
ai_mode_answer = results.get("text_blocks", {})[0].get("snippet", "No answer found")
print(ai_mode_answer)

Today in Sha Tin, the weather features mostly cloudy skies with extreme heat, reaching a high of 91°F (33°C) and dropping to a low of 81°F (27°C) overnight. A Very Hot Weather Warning is currently in force for the region. Conditions feel significantly hotter due to 82% humidity, pushing the "Feels Like" index up to 98°F (37°C). Winds are moving from the south at roughly 9 mph.